services:
  java_db:
    image: postgres:12
    container_name: java_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rammstein
      POSTGRES_DB: crypto_portafolio
    ports:
      - "5432:5432"
    networks:
      - app_network

  java_app:
    build: .
    container_name: java_app
    depends_on:
      - java_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db:5432/crypto_portafolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Rammstein
    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:
