
services:
 java_app:
  container_name: java_app
  image: pee-java-app:1.0.0
  build: .
  ports:
   - 8080:8080
  environment:
   - DATABASE_URL=jdbc:postgresql://java_db:5432/crypto_portafolio
   - DATABASE_USERNAME=USERNAME
   - DATABASE_PASSWORD=PASSWORD
  depends_on:
   - java_db
 java_db:
  container_name: java_db
  image: postgres:12
  ports:
   - 5432:5432
  environment:
   POSTGRES_USER: USERNAME
   POSTGRES_PASSWORD: PASSWORD
   POSTGRES_DB: crypto_portafolio