
services:
  java_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_LOCAL_PORT:-5432}:5432"
    networks:
      - app_network
    volumes: 
      - shared_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7
    ports:
      - "${REDIS_LOCAL_PORT:-6379}:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s


  java_app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      java_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASS}
      FLYWAY_BASELINE_ON_MIGRATE: ${FLYWAY_BASELINE_ON_MIGRATE:-true}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64}
      REFRESH_TOKEN_HASH_SECRET_BASE64: ${REFRESH_TOKEN_HASH_SECRET_BASE64}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}

      API_COINMARKETCAP_BASE_URL: ${API_COINMARKETCAP_BASE_URL}
      COINMARKETCAP_API_KEY: ${COINMARKETCAP_API_KEY}
      API_ALPHAVANTAGE_BASE_URL: ${API_ALPHAVANTAGE_BASE_URL}
      API_ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      API_MASSIVE_BASE_URL: ${API_MASSIVE_BASE_URL}
      MASSIVE_API_KEY: ${MASSIVE_API_KEY}
      POLYGON_API_KEY: ${POLYGON_API_KEY}
      POLYGON_BASE_URL: ${POLYGON_BASE_URL}

      MENSSEGER_ASSETS: ${MENSSEGER_ASSETS}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}	  
    networks:
      - app_network
    ports:
      - "${APP_HOST_PORT:-8080}:8080"

networks:
  app_network:

volumes:
  shared_pg_data:
  redis_data:
