
services:
  java_db:
    image: postgres:12
    container_name: java_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes: 
      - pg_data:/var/lib/postgresql/data

  java_app:
    build: .
    container_name: java_app
    depends_on:
      - java_db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASS}

      API_COINMARKETCAP_BASE_URL: ${API_COINMARKETCAP_BASE_URL}
      API_COINMARKETCAP_API_KEY: ${COINMARKETCAP_API_KEY}
      API_ALPHAVANTAGE_BASE_URL: ${API_ALPHAVANTAGE_BASE_URL}
      API_ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}

    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:

volumes:
  pg_data:
  redis_data:
