services:
  java_db:
    image: postgres:12
    container_name: java_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes: 
      - pg_data:/var/lib/postgresql/data

  java_app:
    build: .
    container_name: java_app
    depends_on:
      - java_db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:

volumes:
  pg_data:
