package com.mx.cryptomonitor.user.domain.model;

public enum AuditEventType {
  USER_REGISTER_SUCCESS,
  USER_REGISTER_CONFLICT,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILED,
  AUTH_LOGOUT_SUCCESS,
  AUTH_LOGOUT_FAILED,
  TOKEN_REFRESH_SUCCESS,
  TOKEN_REFRESH_FAILED,
  REFRESH_TOKEN_REVOKED,
  REFRESH_TOKEN_REVOKE_FAILED,
  TRANSACTION_CREATE_SUCCESS,
  TRANSACTION_CREATE_FAILED,
  TRANSACTION_UPDATE_SUCCESS,
  TRANSACTION_UPDATE_FAILED,
  TRANSACTION_DELETE_SUCCESS,
  TRANSACTION_DELETE_FAILED
}
