package com.mx.cryptomonitor.contract.provider.auth;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.http.MediaType;

import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import au.com.dius.pact.provider.spring.junit5.MockMvcTestTarget;
import au.com.dius.pact.provider.spring.junit5.PactVerificationSpringProvider;

import com.mx.cryptomonitor.integration.user.support.UserModuleIntegrationTest;
import com.mx.cryptomonitor.user.application.dto.request.UserRegistrationRequest;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Provider-side Pact verification for POST /api/v1/auth/login.
 *
 * <p>Reads pacts/frontend-crypto-portfolio-api.json (generated by {@code
 * AuthLoginConsumerPactTest}) and verifies the real Spring application satisfies every interaction
 * declared in that contract. Uses {@link MockMvcTarget} so that no real HTTP port is required:
 * the full Spring Security + filter chain is exercised through MockMvc.
 */
@Tag("contract")
@Provider("crypto-portfolio-api")
@PactFolder("pacts")
@ExtendWith(PactVerificationSpringProvider.class)
class AuthLoginProviderPactIT extends UserModuleIntegrationTest {

  @BeforeEach
  void configurarTarget(PactVerificationContext context) {
    context.setTarget(new MockMvcTestTarget(mockMvc));
  }

  @TestTemplate
  void verificarPactos(PactVerificationContext context) {
    context.verifyInteraction();
  }

  /**
   * Prepara el estado requerido por el contrato: un usuario con email valid@test.com debe existir
   * en la base de datos antes de que Pact ejecute la interacción de login.
   */
  @State("un usuario registrado con email valid@test.com")
  void prepararUsuario() throws Exception {
    UserRegistrationRequest req =
        new UserRegistrationRequest(
            "valid_user",
            "valid@test.com",
            "Secret123!",
            "Valid",
            "User",
            null,
            null,
            null,
            null,
            null,
            null,
            null);
    mockMvc
        .perform(
            post("/api/v1/users/register")
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(req)))
        .andExpect(status().isCreated());
  }
}
